### ISSUE TITLE
 Yml does not exist: course.rb 

### ISSUE THREAD

**Issue by datamove** [autolab/Autolab#1010]
Dear developers,

I have install Autolab usin gone-click option, then logged in as a default admin user, created a new course and assigned default admin user as Instructor for this course.

Then I went on the create an assignment and see the following as warning at the top:

** Yml does not exist: course.rb  Yml does not exist: autolab.log ** 

Indeed there were no courer.rb file in the course dir. I have copied this file from the AutoPopulated course dir, and reloaded the course config file via course manage menu. But this didn't help to get rid of the message.

Also, when I proceeded anyway with creating an assignment from tarball? the page just reloaded. 

Is there something I have done wrong? How to proceed and where to look for more tips? any log file can help me?

Reproduced with one-click setup on ubuntu18.04 and 14.04

Thanks in advance!

**Comment by datamove** [comment]
Thanks! 
What do I have to restart for changes to take effect? Does not seem to work when I restart the three running docker containers

**Comment by skoch9** [comment]
In order to make it work for an already running version you can login to the web_server (or web_local) container. You can do this by running `docker exec -it <web_server_container_id> bash` and then edit the file with `nano app/controllers/assessments_controller.rb`. If you want to make the change permanent you need to commit it to the docker image `docker commit <web_server_container_id> web_server`
