### ISSUE TITLE
Problem installing assessments from a tarball (rails-5-upgrade)

### ISSUE THREAD

**Issue by bernstdh** [autolab/Autolab#1040]
When I install an assessment from a tarball I get a message saying "An assessment with the same name already exists" (though that isn't the case and the assessment is actually installed).

**Comment by fanpu** [comment]
I attempted to replicate it in the following way:

1. Delete the hello assessment from autolab/courses/Autopopulated
2. Upload hello.tar (https://github.com/autolab/Autolab/blob/master/examples/hello.tar) to my own local Autolab instance
3. I get the same error message
4. Ran `Assessment.find_by_name("hello")` in the Rails console, and saw that the entry is still there.
5. Delete the assessment with `Assessment.find_by_name("hello").delete`
6. Attempt to re-upload hello.tar, which works without any error messages

I then tried to replicate it in a different way by deleting the assessment with the Delete Assessment button on the Edit Assessment tab, and then had to remove the files from the courses directory (since it only deletes the entry on the db and not the actual course files on your machine) before uploading it successfully again.

However I am unable replicate exactly what you have faced. If you still remember could you provide a list of the actions that you took before this happened? If not, it appears that it is working as expected and I will close the issue. Thank you!
