### ISSUE TITLE
Ubuntu 1-click link broken

### ISSUE THREAD

**Issue by chelseas** [autolab/Autolab#1109]
I was hoping to do the 1-click install with ubuntu but the link is broken.

**Comment by TheodorJ** [comment]
Hi @chelseas , the 1-click script should work fine with Ubuntu 16.04, but for other versions it's better to follow the steps in our documentation: https://autolab.github.io/docs/

We've been trying to get the 1-click script working on other versions of Ubuntu for a while now, and that's still on our list. We'll update you here if we get a stable version of it working.

**Comment by Mat2095** [comment]
I didn't get the 1-click script working on a clean VM with Ubuntu 16.04 (console log: https://pastebin.com/C5UVDC1a ).
But I didn't really expect it to work since the documentation basically says it is deprecated:

> The OneClick installation is currently broken. We are in the midst of migrating to Docker for installation. Please treat this page as legacy reference.

Should I create an issue for this anyway? If yes, where? The oneclick-repository doesn't seem very active.
@TheodorJ you said that you're working on the 1-click script, so I assume it became deprecated between your answer and now, correct?

**Comment by fanpu** [comment]
Hi @Mat2095, sorry about the delayed response, but the 1-click script is no longer supported and we are no longer maintaining it. We are developing an alternative simple installation method with Docker compose, but it will be a while before it will be ready
