### ISSUE TITLE
VCS integrated assignment submission?

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1149]
I'd like to encourage collaboration on group homework via a VCS like gitlab, but was not able to find built-in support for this functionality.

Currently I'm using quite a dirty hack of post-receive git hook to tar and post committed code from gitlab to autolab, but that requires a lot of manual effort as well as a backdoor at autolab to bypass the authentication mechanism.

This feels quite awkward. Most importantly, normal usage of VCS's (github, gitlab, etc) seem to only support posting a notification JSON message in their webhooks, leaving the responsibility of checking out and building code to the CI engine. (Not sure though, please correct me if I'm wrong)

Is it possible configure autolab to listen on webhook events and pull submitted code automatically?

**Comment by wlnirvana** [comment]
Duplicate of #1034

**Comment by fanpu** [comment]
Hi @wlnirvana, unfortunately at this time we do not have such a feature to listen on webhook events, however this Github integration feature is something that is prioritized. Just for visibility, we are currently planning out a new Dashboards feature for instructors to identify students who are struggling, and implementation would be mainly taking place in the fall. Afterwards, we are strongly considering working on this feature as the Github integration helps to directly provide a lot of telemetry about student progress/performance (from their commit frequency, etc), and also because it is very valuable in general for many classes.

**Comment by fanpu** [comment]
As for implementation details on how the integration will be achieved, it will most likely be via the current Autolab CLI (very possibly with some modifications)

**Comment by victorhuangwq** [comment]
Here is the command line interface that @fanpu was mentioning. It allows students to submit via the command line. https://github.com/autolab/autolab-cli

**Comment by wlnirvana** [comment]
Got it. Thanks guys.

**Comment by GuillaumeDIDIER** [comment]
It is worth noting that Github integration has been released in https://github.com/autolab/Autolab/releases/tag/v2.8.0

(Other VCS are still unsupported)
