### ISSUE TITLE
Migration failure

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1151]
Trying to set up a clean Autolab instance on macOS and run into the following error during `bundle exec rake db:migrate`, which seems to be rails/rails#18868

```txt
== 20100721214856 FixVisibleUntil: migrating ==================================
-- rename_column(:assignments, :visable_until, :visible_at)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Invalid default value for 'visible_at': ALTER TABLE `assignments` CHANGE `visable_until` `visible_at` timestamp DEFAULT NULL
/Users/foobar/projects/Autolab/db/migrate/20100721214856_fix_visible_until.rb:3:in `up'
/Users/foobar/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/foobar/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value for 'visible_at': ALTER TABLE `assignments` CHANGE `visable_until` `visible_at` timestamp DEFAULT NULL
/Users/foobar/projects/Autolab/db/migrate/20100721214856_fix_visible_until.rb:3:in `up'
/Users/foobar/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/foobar/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'

Caused by:
Mysql2::Error: Invalid default value for 'visible_at'
/Users/foobar/projects/Autolab/db/migrate/20100721214856_fix_visible_until.rb:3:in `up'
/Users/foobar/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/foobar/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by fanpu** [comment]
Could I check if you are using the Rails 4 or Rails 5 (master) version of Autolab, as it appears that most people facing it in https://github.com/rails/rails/issues/18868 were on Rails 4 and it was eventually fixed in https://github.com/rails/rails/pull/17822? Thanks!

**Comment by wlnirvana** [comment]
Rails 5.2.0

**Comment by fanpu** [comment]
Thank you, I can replicate this issue and will be looking into it

**Comment by fanpu** [comment]
This is due to MySQL disallowing NULL for timestamps by default (see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/36405 and https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp, server modes where this is enforced: https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html). From what I see there are three ways around it:

1. Disable strict mode in MySQL (set by default with `STRICT_TRANS_TABLES` or `STRICT_ALL_TABLES`)
2. Change all migrations to have default values if MySQL is being used, i.e something like

```
if ActiveRecord::Base.connection_config[:adapter] == 'mysql2'
  t.timestamp :visable_until, :default => "2000-01-01 00:00:00"
else
  t.timestamp :visable_until
end
```

I'm not sure why but using the date '1970-01-01 00:00:00' or even '1970-01-01 00:00:00' still causes MySQL to complain that it is an invalid default value, so I had to use "2000-01-01 00:00:00".

**Comment by wlnirvana** [comment]
Did you mean [00:00:01][1] instead of 00:00:00? 

By the way, I just opened an issue at rails/rails#39251, which might be the root cause (or workaround) from rail's perspective.

[1]:https://dev.mysql.com/doc/refman/5.7/en/datetime.html

**Comment by fanpu** [comment]
Oops, you're right, I meant 00:00:01.

I saw that the issue that you opened, and tried their suggestion to turn `explicit_defaults_for_timestamp=1` in `my.cnf`, which allowed the migrations to run successfully on my machine. Could you try that and see if it works for your setup?

**Comment by wlnirvana** [comment]
Enabling `explicit_defaults_for_timestamp` resolves the issue. Closing.
