### ISSUE TITLE
Annotation on first file (indexed 0) is not correctly persisted

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1186]
For archived submission, annotations on the first file (header position is 0) are persisted in the database with position column as NULL, instead of 0. Root cause seems to be this condition:

https://github.com/autolab/Autolab/blob/c1b8d3b3aef67fb4ae7efdef4995b3024808ee92/app/assets/javascripts/annotations.js#L440-L442

**Comment by wlnirvana** [comment]
Any difference between these two variables?

https://github.com/autolab/Autolab/blob/c1b8d3b3aef67fb4ae7efdef4995b3024808ee92/app/views/submissions/view.html.erb#L27

https://github.com/autolab/Autolab/blob/c1b8d3b3aef67fb4ae7efdef4995b3024808ee92/app/views/submissions/view.html.erb#L30

The latter seems to be introduced in https://github.com/autolab/Autolab/pull/1032/commits/7807025fca7c880d5bb740e516d1898e8a36c0b8#diff-e9a31f44b3de27992bf53828ef25f746R26

**Comment by fanpu** [comment]
Thanks for bringing this up to us! I'll be looking into both issues soon. For the second issue, it seems that `curHeaderPos` is only being used to invalidate the cache in `annotation.js`. I'm checking with my teammate to see what was the rationale for using it versus `currentHeaderPos` (right now it seems like perhaps `curHeaderPos` is essentially immutable while `currentHeaderPos` can be modified, but I can't tell why this would be desirable because users will change between files.

**Comment by wlnirvana** [comment]
Maybe position=NULL is supposed to be used for direct source file (.c, .java, etc) submission. Unfortunately 0 (for first file of archive) and NULL (for source file) are handled indistinguishably somewhere, resulting in the bug.

**Comment by fanpu** [comment]
@wlnirvana  Is it possible to give me some instructions on how I can replicate this issue (such that annotations would be affected)? When I tried uploading archives/zip it seems that the file at position 0 is always `/` or `./` and it's not possible to create annotations on them, but I might be missing something. Thanks!

**Comment by damianhxy** [comment]
Fixed in #1220
