### ISSUE TITLE
Remark links on View Feedback page result in 500 responses

### ISSUE THREAD

**Issue by javb99** [autolab/Autolab#1315]
**Your environment**
Let us know details such as 
- WSUV's Autolab at https://autolab.encs.vancouver.wsu.edu
- WSUV is on commit: 30f198e
- Safari on macOS Big Sur

**Steps To Reproduce**
1. Go to 'https://autolab.encs.vancouver.wsu.edu/courses/course/assessments/astar/viewFeedback?feedback=id&submission_id=id'
2. Click on TA feedback at the bottom of the page
3. See error

**Current behavior**
Opens to a 500 server error page

**Expected behavior**
Opens the submission source file with that specific feedback line visible

**Screenshots**
<img width="698" alt="Screen Shot 2021-04-05 at 11 59 50 AM" src="https://user-images.githubusercontent.com/8713084/113613826-993fd680-9606-11eb-81fc-6059663b7f9e.png">

Result:
<img width="1330" alt="Screen Shot 2021-04-05 at 12 00 22 PM" src="https://user-images.githubusercontent.com/8713084/113613935-b5437800-9606-11eb-9a8d-3e172c3b9975.png">

Expected Result:
<img width="1317" alt="Screen Shot 2021-04-05 at 12 02 24 PM" src="https://user-images.githubusercontent.com/8713084/113614291-27b45800-9607-11eb-86ce-5b1e180425eb.png">

**Comment by amartinez116** [comment]
Hi,

There have been two "Remarks" related bug fixes since the commit you are currently on:

Remarks if grades have not been released: https://github.com/autolab/Autolab/pull/1292
Remarks on non-archive file: https://github.com/autolab/Autolab/pull/1283

However, I believe the issue you are facing might have to do with #1292. Can you confirm whether the grades have been released for that assignment? Students should only be able to view TA feedback after the grading deadline has passed and those grades have been released which is what #1292 fixes.

Thanks!

**Comment by javb99** [comment]
The grades have been released for that assignment. It doesn't seem related to #1292 or #1292 based on their titles.

**Comment by damianhxy** [comment]
I am unable to reproduce the issue, if possible could you attach any logs?

**Comment by damianhxy** [comment]
Closing this as stale.

As far as I can tell, this isn't an issue anymore. When grades are released, the links work as expected. When grades are not released (or grading deadline is not past), the remarks section does not appear.
