### ISSUE TITLE
Allow submission of exact same file

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#143]

**Comment by Z1MM32M4N** [comment]
What's the usefulness of this? It seems to me like the real issue is that we should either allow students to force a regrade (for which the current workaround is to change the content of a submission marginally), or to simply alert a student that they've handed in an identical submission. What outcome does this hope to fix, assuming that all of the grading system is working perfectly?

**Comment by ymzong** [comment]
@Z1MM32M4N We can further discuss this in Slack. :)

**Comment by icanberk** [comment]
I guess this is fixed now? @mihirpandya

**Comment by ymzong** [comment]
@icanberk This was fixed last night right before our meeting with Dave.
