### ISSUE TITLE
Student watchlist screen should not include students marked as dropped

### ISSUE THREAD

**Issue by zackw** [autolab/Autolab#1611]
**Your environment**
Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/

**Steps To Reproduce**

1. Have a class with a bunch of assignments, where some students drop the class only *after* failing to turn anything in for one or more assignments.
2. Enable "did not submit one or more assignments" monitoring.
3. Upload an official roster for the class in "add/drop" mode, or otherwise mark these students as dropped.
4. Visit the watchlist screen.

**Current behavior**

Students show up on the watchlist screen even though they have dropped the course and Autolab knows this.

**Desired behavior**

Students who are marked as dropped should not appear on the watchlist screen.  (However, if they are later _un_-marked as having dropped the course -- for instance, if the instructor was manually tagging drops and made a mistake -- then they should reappear on the watchlist screen if they meet the criteria.)

**Comment by victorhuangwq** [comment]
Hi Zack, 

What I would do is to:
- Hide the students who are dropped from being displayed in the watchlist
- Prevent students who are dropped from being considered when refreshing the metrics
- Prevent students who are dropped from being considered when changing the conditions

How does that sound?

**Comment by victorhuangwq** [comment]
@zackw any comments?

**Comment by gfieni2022** [comment]
Hello,

I agree with Zack's latest comment. As a class that has 60+ dropped students currently, each time I update the metrics, I have to go through the list of dropped students and manually resolve each student. It is very time consuming and would be much easier if there was a filter that could do this task for me. 

Also, simply adding students who have dropped to archived would not help the problem. Currently if you have already moved a student to archived, they still show up in the list when you re-configure the metrics. 

The best and most efficient method for me to use a feature like this would be able to exclude all students who have dropped when I set the metric configurations, since I try to update them every few weeks. 

I think it is okay to "hide" the instance of a dropped student from the watchlist in this case because usually dropped students show up as the most "drastic" students in the list (mostly because they have probably not submitted 1+ assignments) and thus pollute the list so that I can't tell the students who are the most in need of help.

**Comment by victorhuangwq** [comment]
@gfieni2022 thank you for your comment. 

But I want to point out that we will also prevent the students from being considered when you update the list. So the point that you mention about reappearing shouldn't be an issue.

What do you think about that?

**Comment by victorhuangwq** [comment]
Okay so here's what I'm hearing @gfieni2022 

- Refreshing the list should remove dropped students
- Updating the conditions should prevent dropped students from being considered and reappearing in the list

Does this sound good?

**Comment by victorhuangwq** [comment]
@gfieni2022 Do take your time to look at the screenshots in the Pull Request linked and see if flow makes sense to you

**Comment by gfieni2022** [comment]
Yes, both of those points sound good to me. 

And yes, the screenshots and the workflow they show look great to me! Thank you for taking my feedback!
