### ISSUE TITLE
The submitted PDF file was downloaded as an invalid zip file

### ISSUE THREAD

**Issue by Hao-Kang** [autolab/Autolab#1644]
**Your environment**
- Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/

**Steps To Reproduce**
1. Go to individual submission with a **PDF** file
2. Click on `Download` button
3. Try to decompress locally

**Current behavior**
The entire PDF file is downloaded as a zip file, which is unable to unzip. 
This is quite annoying, as I have to rename the file with `.pdf` extension at the end.

**Expected behavior**
Should download a valid zip file that the user can decompress.

**Screenshots**
![image](https://user-images.githubusercontent.com/89672451/201984039-b1d59ac2-14f1-4e6b-9c0d-9182d0e8745b.png)
![image](https://user-images.githubusercontent.com/89672451/201984159-4d66d7e3-46db-426a-8b6f-93daa793e7e1.png)
![image](https://user-images.githubusercontent.com/89672451/201984325-33b5813d-8462-4bff-89cb-384bf3facf4d.png)

**Comment by damianhxy** [comment]
Hi Hao Kang,

The issue here is that the handin format for the assessment was not properly configured (Edit Assessment > Handin). For downloads to work correctly, it should be set to a filename ending with `.pdf`.

![Screenshot 2022-11-15 at 18 17 39](https://user-images.githubusercontent.com/9074856/202045226-c4929571-fc1a-4826-8b3a-3ee9d23f461a.png)

As can be seen in your screenshot, the files are given `zip` file extensions as a result.

Hope this helps!

**Comment by damianhxy** [comment]
I believe with #1638, a warning will be displayed in the future, allowing you to correct the issue before students submit.

**Comment by Hao-Kang** [comment]
Ok, but what if there can be multiple file types, like `.py`, `.pdf`, or `.docx`? Do you recommend just let students compress into `.zip` and submit?

**Comment by Hao-Kang** [comment]
Duplicated with Previous Issues #1638 #951
