### ISSUE TITLE
Cannot upload roster to AutoLab

### ISSUE THREAD

**Issue by ProfMatthewHz** [autolab/Autolab#1971]
This is a file of my own creation, but one I have done every term and so should work. When I upload it, however, I am getting the Donkey Kong error page.

[CSE442ClassRoster.csv](https://github.com/autolab/Autolab/files/12454858/CSE442ClassRoster.csv)

**Comment by ProfMatthewHz** [comment]
The CSE IT tool's classlist tool import does work, but why is that needed? Especially since I cannot upload all sections at once.

**Comment by damianhxy** [comment]
Hi Matthew, rosters must provide a first name and/or a last name for each student -- is that the exact CSV that you are using?

![Screenshot 2023-08-28 at 17 07 57](https://github.com/autolab/Autolab/assets/9074856/a7638b50-4bc7-49df-b68c-8f2b277c72d9)

(the Donkey Kong is due to an unrelated issue where too many errors cause a Cookie Overflow)

**Comment by damianhxy** [comment]
Closing as stale. Reopen this if you're still facing an issue!
