### ISSUE TITLE
Improve Gradebook UI/UX

### ISSUE THREAD

**Issue by damianhxy** [autolab/Autolab#2034]
- Assessment headers are generally unreadable -> need a way to delete unused columns (persistently) and easily reformat the remaining columns
- Right-click menu entries are grayed even though they're not disabled

**Comment by KesterTan** [comment]
- Grayed out column when a user right-clicks is too long and not intuitive

**Comment by KesterTan** [comment]
- The grey color is not inclusive for people who are visually impaired because of the low contrast
- Changes are not sticky when the page is refreshed.
- Having multiple columns labelled version is confusing.

**Comment by KesterTan** [comment]
Consider:
- Slick.Plugins.HeaderButtons to allow for resize of columns
- Use ticks like in [this example](https://6pac.github.io/SlickGrid/examples/example-grid-menu.html) or [this](https://6pac.github.io/SlickGrid/examples/example-frozen-columns.html)to make menu more intuitive, should also change the background color. We can also add an option to save the config to make this sticky.
- Adding a [dropdown](https://6pac.github.io/SlickGrid/examples/example-row-detail-selection-and-move.html) at each row which when clicked will bring up a popup about data attributed to that row
- Group version and assessment name together like [this](https://6pac.github.io/SlickGrid/examples/example-grouping.html) so that each version is grouped with its corresponding assessment
