### ISSUE TITLE
Manage accounts: Search on email, first, and last

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#212]
On the Manage Accounts page, the search operation is only looking at the email address. It should include First and Last name as well.

**Comment by dlbucci** [comment]
Thought this would be an easy fix, but I actually can't figure out how the filtering is occurring on this page.  It has something to do with using a 5 year old jQuery plugin called datatables and it magically handles it, but only on the email column for some reason.  A total JS update may be warranted.

**Comment by Z1MM32M4N** [comment]
I'm not sure that this particular page is being controlled via DataTables, but I know that there certainly are pages that use that plugin. The real issue I see here is that we're using three different methods for drawing tables: Slick grids, DataTables, and the vanilla JavaScript being used on this page. The end goal would be to standardize that so that all tables look and feel the same way.

**Comment by namanbharadwaj** [comment]
btw, it seems like it *does* look at email, first, and last name, but is case sensitive, so a fix might actually be as easy as standardizing cases.

**Comment by dlbucci** [comment]
It's not using DataTables, its using sorttable.  And if that doesn't load or run (which it actually hadn't been doing for a long time before it was recently fixed), then there's no pagination, but filtering works on everything.
Also, I was looking at the Manage Submissions page which (also?) uses sorttable and only filters on emails.
I think that unifying our table solutions/JS would be a very good idea.
