### ISSUE TITLE
Internal error when resending a confirmation email after signup

### ISSUE THREAD

**Issue by quietspoon** [autolab/Autolab#2161]
**Your environment**
- Autolab version: Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/
- Operating system: macOS Sonoma 14.4.1
- Web Browser: Google Chrome

**Steps To Reproduce**
1. New student sign up
2. Create new account using andrew cmu email
3. Encountered 500 internal error upon submission
4. Go to https://beta.autolabproject.com/auth/users/confirmation
5. Attempt to resend confirmation using same andrew cmu email
6. Encountered 500 internal error upon submission

**Current behavior**
Unable to confirm account or sign in

**Expected behavior**
The ability to create an account, confirm account email, and sign in

**Screenshots**
Screen shot of response after attempting to re-send confirmation email
![autolab_500_response](https://github.com/autolab/Autolab/assets/168950052/58ed5b26-8941-48f4-8756-c802c25f6127)

**Comment by evanyeyeye** [comment]
Thanks for the issue report! I assume you are taking a summer course at CMU. The instance for that is currently set up to only use Google OAuth for signups and logins. The errors you have experienced is due to there being no mailing server configured, which is required by the default signup method. We will work on providing an indication of this for students, and apologies for any confusion.

Issue will be marked as closed. Feel free to re-open it or contact me if you experience any other issues.
