### ISSUE TITLE
Scoreboards need numbered rows

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#289]
Somewhere in the transition to the new system, scoreboards lost their numbered rows (starting at 1 on the lefthand side). These are very helpful to instructors and should be reinstated.

**Comment by jez** [comment]
After looking into this issue, some poor attempts at modularization are preventing this from being the simple change that I thought it would. It turns out that this will involve changing a method that can right now be overridden in an assessment's config file. Once we've cleaned up config files and have a way to warn instructors about changes to them (#227), this becomes a 10-line fix.
