### ISSUE TITLE
Jobs page Completed link no longer shows feedback file

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#326]
When you click on the "Completed" link on a completed job, it should display the feedback file, but it doesn't, instead reporting "None available". This was working properly one week ago.

**Comment by dlbucci** [comment]
I know why this is happening, and will try to fix it.

**Comment by dlbucci** [comment]
There's not really an easy fix for this.  Essentially, jobs_controller previously parsed the notifyURL to figure out the submission the feedback belonged to, then it would find the Score model for that submission that contained the Autograder output.  But now, the notifyURL doesn't include the submission_id, with good reason, and instead includes a dave key to indicate which submissions are affected.
This key gets nullified when feedback is saved so that submissions can't get feedback multiple times unless they are resent, so we can't really use the notifyURL to find out where the feedback got saved.
The only other option I see right now would be parsing the localFile for an email, and version, and then searching for the submission based on those and the current assessment, but I think that would be slow, and also very brittle.

**Comment by icanberk** [comment]
How about also passing submission_id as a parameter in notifyURL ?

**Comment by dlbucci** [comment]
Eh, that seems like a hack to me, although I can't see why it wouldn't work, so I'll try that.  It would probably be best to get my retry_autograde hotfix in first though, because it also added a parameter to the callbackURL.

**Comment by dlbucci** [comment]
Fixed by #342
