### ISSUE TITLE
CourseUserData should have an email column

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#418]
There are several places in our code where we want to know a CUD's email address, which forces us to load the CUD's user for that sole purpose. If we stashed a copy of each CUD's email in the CUD table, we could save a lot of DB reads.

**Comment by ymzong** [comment]
Agreed. The current test framework also relies on getting `CUD.email`.

**Comment by icanberk** [comment]
Isn't there a better way of doing this than adding a new column to the DB? We definitely need this for performance purposes but I feel like it's semantically incorrect and will make the code more confusing.

**Comment by jez** [comment]
What is the CUD table? Where would we actually be storing the value, and
where does it "belong"? (I'm trying to understand why this is maybe
unsemantic)

**Comment by dlbucci** [comment]
I don't think it's very incorrect.  It's duplication for sure, but for a good reason.  The CUD table is the join table between Courses and Users.  Users have unique emails, so email 'belongs' there, but CUDs also have the same unique email, so it's not too unreasonable to put it there.

**Comment by zyx-billy** [comment]
"Incorrect" perhaps isn't the best word for it, since there's something called [denormalization](https://en.wikipedia.org/wiki/Denormalization).

From what I read, denormalization itself isn't bad. Using it unwarranted is. Was there anywhere specific in the application that was too slow, and can be fixed by adding this column? If there's no problem, I don't think it's worth duplicating the column and having to worry about data consistency right now. We'll certainly consider this as a possible solution if we ever encounter such a problem in the future. (Closing for now).
