### ISSUE TITLE
Support for programming contests and self-study courses

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#420]
It would be really cool to have a feature that allows instructors to offer courses that anyone can sign up for, without having to explicitly added to the course by the instructor. If we had this feature, then we could use Autolab for things like self-study courses and programming contests.

**Comment by mihirpandya** [comment]
So on top of allowing anyone to sign up for an existing course on Autolab, we would also need to provide additional information about the course like Schedule, Syllabus, Lecture Notes, Announcements and other logistical information that would otherwise be provided in classrooms.

**Comment by ymzong** [comment]
I think instructors themselves can host a site with schedule, syllabus, etc., and use Autolab mainly for grading purposes (like in Kosbie's 15-112 site `http://www.kosbie.net/cmu/spring-15/15-112/`).

**Comment by jez** [comment]
Yeah, I think we should prefer setting up an external site for the
information related to the event not the auto grading.

**Comment by jez** [comment]
Maybe we can add support to link to a "course website"?

**Comment by TheodorJ** [comment]
Maybe we can support a course "type" system:

When an instructor creates a course, they can select a type. It can be a class, a contest, an interview, or an "other". This way, we can use existent code to manage courses, but when an instructor views a list of their courses they are separated by type. Organizations hosting programming contests can host their own website with event-related information and a link to that Autolab course, which would be of type "contest".

In addition, we should add an extra feature so that an Instructor creating a course can choose whether to allow students to register themselves for the course. This way, we don't need any complicated methods to register contestants for programming challenges; instead, the organization posts a link to the course and the contestants register themselves.

**Comment by damianhxy** [comment]
Closing as stale (there are better platforms for programming contests out there)
