### ISSUE TITLE
Gradesheet graders should only change if the feedback/score changes.

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#446]
Currently if a grader clicks a score, does nothing and clicks away, the score will get saved with that user being the grader, which is incorrect.

**Comment by zyx-billy** [comment]
(Thought I'd fix the gradesheet-related issues while I'm working on the page...)

Here's a related issue that could be solved at the same time: when the feedback popover is on, clicking away also saves the feedback, which makes the "Save" button useless, and also confusing (people might make a mistake, and hope clicking away will cancel the change). 

One solution for both problems could be to add a "cancel" button to the popover, and disable the close-popover-by-clicking-somewhere-else feature. OR how about we just redo the entire feedback editing box (since it's really small & inconvenient when the feedback's long: see #570), like having a large editing box anchored to the side of the table.

**Comment by ymzong** [comment]
@zyx-billy I think modifying the size and buttons on the feedback box suffices as our short-term solution, and we can see how well that goes before doing major changes like pulling feedback box to the side.

**Comment by zyx-billy** [comment]
Sure. I'll implement the first solution and see how that goes.

**Comment by zyx-billy** [comment]
The popover looks like this with the cancel button (using default Autolab btn):
![feedback_cancel_button](https://cloud.githubusercontent.com/assets/3676913/14184766/d5952330-f744-11e5-9a95-bc31486cb104.png)

I hope this can make the consequences explicit, so nothing is saved (or discarded) unintentionally. However, clicking away is ignored, and it feels a bit weird. Perhaps we should add some visual cues?

**Comment by nayak16** [comment]
I agree that it is weird. Why can't we close the feedback box after clicking away? Basically having the same action as pressing the Cancel button.

**Comment by zyx-billy** [comment]
@nayak16 So I was worried someone might accidentally click somewhere else and lose everything they wrote since the box is kinda small...

**Comment by nayak16** [comment]
@zyx-billy Is this close to being resolved? We want to get all the gradesheet changes in before deploying to production.

**Comment by zyx-billy** [comment]
@nayak16 I can get it done by today if needed, there's not too much to change. Are we still targeting Apr12 or is it gonna be earlier?

**Comment by ymzong** [comment]
@zyx-billy The final pull day for Computing Services is Apr 12th, and I'd say we should aim for code freeze by April 7th (our next meeting).

**Comment by zyx-billy** [comment]
OK, so I'll make sure it's ready for demo on this week's meeting.

**Comment by ymzong** [comment]
@zyx-billy  :+1:, and don't forget to base it on `master`!

**Comment by zyx-billy** [comment]
@ymzong The previous pr changed the gradesheet's JS file a lot, and I will continue modifying the same file for this issue. I think it'll be easier to have this based on the latest pr to prevent dealing with merge conflicts?

**Comment by ymzong** [comment]
@zyx-billy Sure, go ahead!

**Comment by zyx-billy** [comment]
fixed with #651
