### ISSUE TITLE
Interaction between grace days and groups

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#518]
Lujo Bauer has pointed out that if groups change over the semester, the grace day calculations are wrong, giving too many grace days, seeming to always give grace days matching the largest number available to the group members at that time.

**Comment by dlbucci** [comment]
I can take a look at this.  Should the correct behavior be that a group always has the fewest number of grace days available for all of its members, or that each member gets the grace days calculated separately?

**Comment by droh** [comment]
Each member should have their grace days computed separately.


-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by zyx-billy** [comment]
Could this have been fixed already? Right now grace days do seem to be calculated individually:
Suppose we have two students A and B. A already used all his grace days, but B didn't use any. If they form a group for the next assignment and submit one day late, A would incur a penalty late day while B would not (B would use a grace day). So they would get different 'total scores'.
This happens naturally because the way Autolab handles groups right now is it creates separate submissions for each group member. Each submission record will get filled with the same autograde response (if autograder used), but they're still independent records, so grace days and penalties are calculated independently.
Is this the behavior we want?

**Comment by devanshk** [comment]
@droh This seems to be fixed, can you double-check and confirm that it works the way it should?

**Comment by victorhuangwq** [comment]
Issue seems to be fixed. Closing
