### ISSUE TITLE
Travis CI integration should migrate to containers

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#572]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

We currently get a notice about this when we run travis ci tests.  Also, our travis ci always fails for external PRs, which we should fix.

**Comment by zyx-billy** [comment]
As of right now, Travis no longer issues any notice asking us to migrate to containers (the linked page doesn't even exist anymore). However, as long as we don't need sudo, we really could consider migrating to take advantage of faster build times.

Regarding travis failing for external PRs, that's because we've been using cmu machines as the tango endpoint during travis tests. Access to these machines are stored as encrypted env variables, which we don't grant to external users. We really should figure out a better way to do tango-involved testing on travis without using external services.

**Comment by damianhxy** [comment]
Travis CI is no longer in use.
