### ISSUE TITLE
Authorization for course_user_data#show

### ISSUE THREAD

**Issue by pbamotra** [autolab/Autolab#609]
I'm not sure if this is an issue but I see that 
https://autolab.cs.cmu.edu/courses/COURSE_NAME/course_user_data/SOME_NUMBER is a GET request. It exposes the nicknames at the least, I didn't try editing the info though but yeah I can see the names-nicknames info. I know my SOME_NUMBER and I can do SOME_NUMBER +- (n) and see other person's info.

**Comment by dlbucci** [comment]
Thanks for the heads up, but I don't think this is a serious issue.  Additionally, the route being a GET request really doesn't have anything to do with the actual issue though. GET is just a HTTP method that means you are reading a resource, which is what is occurring here.

The real issue is that there's no authorization for the course_user_data#show route, aside from assuring that user is registered to the course.  All other routes seem to have proper authorization so a student shouldn't be able to edit another student.  There's nothing super secret about the page either, so it's okay if one student can see another student, but we should probably either add authorization to that route or hide the edit information link when appropriate.

**Comment by nayak16** [comment]
Merged in Master
