### ISSUE TITLE
File re-submission fails after pressing back button

### ISSUE THREAD

**Issue by nayak16** [autolab/Autolab#631]
Steps to recreate bug:
1. Submit a file for an assessment
2. Press back button on browser
3. Attempt to resubmit same file
4. Re-submission fails unless a page refresh happens

My guess is that the problem is a caching issue with the file name since submitting another file works.
Best place to start would be `app/controllers/assessment/handin.rb`

**Comment by ymzong** [comment]
I'm guessing that it's more like a front-end issue. The submission button has a protection mechanism that prevents anyone from submitting a same file twice. That's why when you submit some file (say `a.tar`), BACK, then submit the same file again, the browser knows it's the same file and prevents it.

**Comment by nayak16** [comment]
Is this still an issue though? Or something that cannot be prevented?

**Comment by ymzong** [comment]
Checking to see if #641 fixes this.

**Comment by ymzong** [comment]
Fixed by #641.
