### ISSUE TITLE
Annotations Weirdness with '%'

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#653]
As in the issue recently reported to us, when a TA's annotation includes the percentage sign, the annotation functions on student submission page are all unresponsive.

I'm guessing that it has to do with `annotations.js` and Javascript string escaping. Any Javascript wizard wanna help out?

**Comment by zyx-billy** [comment]
It seems the issue is with one function call in annotations.js: decodeURI.

The annotations object (created by rails' to_json function) isn't uri encoded, so there's no need to decode it. This is why having a '%' in the annotation causes a 'malformed URI' error.
After removing the decodeURI function and just using the raw string, the page is able to work fine (also tested with some other special characters).

**Comment by ymzong** [comment]
Yup exactly -- I was roughly looking for decodeURI but didn't find it.

Could you send in a quick PR for it into master?

**Comment by zyx-billy** [comment]
Cool. I'll push a pr now
