### ISSUE TITLE
Feedback text box is inconsistently grayed out.

### ISSUE THREAD

**Issue by hemanthkini** [autolab/Autolab#656]
As in the picture below, the feedback box for an assignment is inconsistently grayed out and unable to be filled in. I've reproduced this consistently on Windows 10, across both Google Chrome and Microsoft Edge. (Sometimes it's editable, but usually not.) FWIW, I didn't notice this issue the last time I graded an assignment (about ~3 weeks ago.)

![image](https://cloud.githubusercontent.com/assets/3934055/14622999/064415bc-0583-11e6-85bf-e5630817ca92.png)

**Comment by hemanthkini** [comment]
As a followup - feedback entry doesn't work on Chrome on Ubuntu 15.04, but it does work on Chrome on OS X.

**Comment by zyx-billy** [comment]
Hi! Sorry about the problem. We just deployed an update to Autolab, which introduced this issue.

A small bug caused the textbox to be grayed out forever when no score exists for the problem. 
We'll try to fix this soon, but before a fix is pushed out, here's a way to enter feedback:
For all the scores you intend to edit, click the score so that the popover shows up (it's ok if it's grayed out), then click elsewhere to hide the popover. Refresh the page. Now the textboxes are editable and saveable.

(Basically, in this case, a textbox becomes editable only after being closed once. This is what's causing the "inconsistent" behavior, and it should be platform independent)

**Comment by hemanthkini** [comment]
Just following up and wanted to confirm that your suggestion works perfectly! Thanks.

**Comment by zyx-billy** [comment]
@hemanthkini, glad to tell you a fix for this problem has been released. Let me know if things work for you. Feel free to close the issue if it does.

**Comment by hemanthkini** [comment]
Yup, it works! Thank you :)
