### ISSUE TITLE
Exported assessment is missing required fields

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#66]
When I export an assessment, the category field is not present in the .yml file.

Concretely, when I export https://milkshark.ics.cs.cmu.edu/courses/14/assessments/49 , I'd expect the yml file dumped to AFS and downloaded to include the line

  category: Programming

And the old Autolab includes this line. The absence of this line confuses Autolab when I try to import. (Not bad confused, but it unnecessarily requires me to give a category. With the category line present in the yml file, the assignment just imports directly.)

**Comment by ymzong** [comment]
Hi @robsimmons, this was actually an intentional design on our side.

In the current case, when an instructor exports then later imports an assessment, s/he has the chance to re-pick the category for the assessment, as we assumed that categories might change over different semesters.

Do you think this makes sense, or would you still want `Category` to be included in the export?

**Comment by robsimmons** [comment]
This is annoying for a specific 122 workflow, which is that this semester I'm going to be creating assignments for Pittsburgh 122, exporting them, and copying them to Qatar 122. It's not the end of the world, though.

**Comment by icanberk** [comment]
This should be fixed once we complete #42

**Comment by jez** [comment]
@ican not sure if this one should be closed
