### ISSUE TITLE
Feature Request: bring back tabbing through scores in the gradesheet!

### ISSUE THREAD

**Issue by krivers** [autolab/Autolab#736]
Our TAs miss being able to tab through scores while entering them by hand in the gradebook. Can we get that back?

**Comment by remzr7** [comment]
We think this feature was removed with #643 and we're investigating bringing it back

**Comment by zyx-billy** [comment]
This has been requested multiple times, and really should be added back to the gradesheet. However, as pointed out in #905, updating a score causes a noticeable delay as the change is sent to the server, and a new total is calculated (based on course-specific configs) and sent back. Ideally, the gradesheet should be updated so that syncing happens in the background, and the user is allowed to quickly tab through scores and make changes.
Since #905 describes a more comprehensive issue regarding the gradesheet, I'm going to close this one, and discussions on how exactly to improve the gradesheet can happen in that thread.
