### ISSUE TITLE
validation error when saving course_user_datum does not explain the problem

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#757]
if CourseUserDatum#create fails due to a validation, it just says "The user with email #{email} could not be created". It does not display the results of validation (as http://guides.rubyonrails.org/active_record_validations.html#displaying-validation-errors-in-views would)

**Comment by TheodorJ** [comment]
How did/do you deliberately cause validation errors when creating new users? I need to test out a few solutions.

**Comment by nayak16** [comment]
Try an email that already exists @TheodorJ

**Comment by TheodorJ** [comment]
@nayak16 I tried that and it threw a MySQL "Duplicate entry 'user0_autopopulated@foo.bar' for key 'index_users_on_email'" error. This happened when user.save was called in user_controller.rb, so I'll try moving the validation error clause into the same function so that it will check for validation errors before SQL errors like this one happen.

**Comment by cg2v** [comment]
The place I (and some faculty) were seeing it was missing first name and/or last name

**Comment by TheodorJ** [comment]
@cg2v That's odd. I tried creating users with missing first and last name fields, and instead of throwing a validation error, it simply flashes "User creation failed" and lists which field is missing. If this is the only case, I could add a note that says which fields are required, which would likely solve the issue.

**Comment by cg2v** [comment]
What I get is "The user with email something@andrew.cmu.edu could not be created"
That is, unless the username is already in autolab due to having logged in or being in another class, in which case the name is autofilled from the existing user record.

**Comment by nayak16** [comment]
Merged 3d32d55
