### ISSUE TITLE
Slow "Manage Submissions" page, potentially due to missing index in database schema

### ISSUE THREAD

**Issue by pcbouman-eur** [autolab/Autolab#890]
After using our Autolab installation for a number of courses, I noticed that the "Manage Submissions" page of an assessment (where the url ends with `/submissions`) loads slow (up to seconds), suggesting an inefficient database query. After some digging I noticed that the assessment controller (i.e. `/app/controllers/assessments_controller.rb`) contains two double joins on the submissions, scores and problems tables, for example in lines 460-468:
```
    results = @submissions.select("submissions.id AS submission_id",
                                  "problems.id AS problem_id",
                                  "scores.id AS score_id",
                                  "scores.*")
              .joins("LEFT JOIN problems ON
        submissions.assessment_id = problems.assessment_id")
              .joins("LEFT JOIN scores ON
        (submissions.id = scores.submission_id
        AND problems.id = scores.problem_id)")
```
I noticed that in the database schema the submissions and scores table both have indexes defined on them, but the problems table does not. It is probably a good idea to put an index on assessment_id in the schema.

**Comment by zyx-billy** [comment]
Thanks for pointing this out. The manage submissions page does seem to be quite slow when the class size is large. Mainly due to a batch of inefficient database queries. However, it doesn't seem like the problems table lacking an index is the problem (the code excerpt from `assessments_controller.rb` isn't the part that loads this page).
The Manage Submissions page, which is used for instructors to view all submissions of an assessment, belongs to the action `submissions#index` (in `submissions_controller.rb`). The inefficient db queries were performed when constructing the view, in which user data for each user was fetched individually in a for loop instead of fetched in batch. It would certainly help if they're all prefetched. A good example is how the gradesheet page works, using AssociationCache. I'm going to label this and we can try to get it fixed.
