### ISSUE TITLE
Unable to regrade - gets 404 Page not found

### ISSUE THREAD

**Issue by rosecatherinek** [autolab/Autolab#935]
Hi Team,

I am a TA for a course. I need to regrade a student's submission. For this, I go to:
Admin Options --> Manage Submissions --> Select the entry and click on the circular arrow that says - rerun the autograder on this submission.

But, shows me this:

**Autolab
404 - Page not found
Oops! The page you are looking for could not be found.
Autolab Home
Questions or problems? Please contact us.**

What could be the problem? Would you need additional info to fix this?

**Comment by pjztam** [comment]
Issue seems Chrome specific (at least for me)

browsers where button works:

- Microsoft Edge
```
Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299
```

- Microsoft Internet Explorer
```
Version: 11.248316299.0
```

IE is an interesting case... the issue seems intermittent. Sometimes clicking the button will  produce a 404, other times it will not.

- Firefox Quantum
```
58.0.2 (64-bit)
```

browsers where button doesn't work:

- Google Chrome 
```
Version 64.0.3282.186 (Official Build) (64-bit)
```

I think that the issue might be related to this

https://stackoverflow.com/questions/7465919/rails-link-to-method-geting-when-it-should-delete

Maybe Chrome isn't loading the JS properly, or you guys are using an outdated version of these particular packages. 

One of my fellow TAs also has this issue, but on Firefox.

I also thought that this might be an issue with installed extensions, but I tried this on Chrome in a VM so that any installed extensions wouldn't be an issue.

## Workaround:

I guess this isn't really a huge issue, because there's an easy workaround.

You can just select a student submission via the checkbox and hit the regrade selection button.

**Comment by victorhuangwq** [comment]
should be addressed in this PR https://github.com/autolab/Autolab/pull/1193
