### ISSUE TITLE
scheduler job disable

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#955]
scheduler jobs should have an enable checkbox, so they can be disabled without being deleted or setting a bogus next time.

A "don't run after" time value may also be useful

**Comment by victorhuangwq** [comment]
May I understand which page / feature is this referring to?

**Comment by cg2v** [comment]
this is https://autolab-dev.andrew.cmu.edu/courses/compserv-mock/schedulers/new (or edit)

**Comment by cg2v** [comment]
The issue is that things like bomblab and attacklab are set up the 3rd week of the semester, and then run forever, until I manually remove them from the database the next semester when I find 6 copies of bomblabUpdater running,

**Comment by cg2v** [comment]
It would also be nice if scheduler jobs automatically disable themselves if they throw (repeated?) exceptions.

**Comment by damianhxy** [comment]
A disabled checkbox and "until" field sound good to me -- I'll work on adding them.

The auto disable feature doesn't seem worth implementing for now, since instructors could wrap their code in a try-catch block. There's also the issue of picking a good threshold, and the complexity of making it an opt-in feature.
