### ISSUE TITLE
jquery and other resources are blocked by GFW for Chinese autolab Users

### ISSUE THREAD

**Issue by jeffchy** [autolab/Autolab#968]
I'm a Chinese user of autolab. Many important resources including jquery and flatpickr are blocked due to "some" reasons. This will cause internal Server Errors if you deployed the Autolab in China.
The problems can be easily solved by change the file to add an accessible cdn for China : 
### for jquery ,bootstrap and many other resources ..
change [Autolab/app/helpers/application_helper.rb]
<pre><code>
  def external_stylesheet_link_tag(library, version)
    cloudflare = "//cdnjs.cloudflare.com/ajax/libs"
    google = "//ajax.googleapis.com/ajax/libs"
    boot = "https://cdn.bootcss.com/"

    case library
    when "bootstrap"
      stylesheet_link_tag "#{boot}/bootstrap/#{version}/css/bootstrap.min.css"
    when "jquery-ui"
      stylesheet_link_tag "#{boot}/jqueryui/#{version}/jquery-ui.css"
    end
  end

  def external_javascript_include_tag(library, version)
    cloudflare = "//cdnjs.cloudflare.com/ajax/libs"
    google = "//ajax.googleapis.com/ajax/libs"
    boot = "https://cdn.bootcss.com/"

    case library
    when "jquery"
      javascript_include_tag "#{boot}/jquery/#{version}/jquery.min.js"
    when "jquery-ui"
      javascript_include_tag "#{boot}/jqueryui/#{version}/jquery-ui.min.js"
    when "prototype"
      javascript_include_tag "#{boot}/prototype/#{version}/prototype.js"
    when "lodash"
      javascript_include_tag "#{boot}/lodash.js/#{version}/lodash.min.js"
    when "backbone"
      javascript_include_tag "#{boot}/backbone.js/#{version}/backbone-min.js"
    when "backbone-relational"
      javascript_include_tag "#{boot}/backbone-relational/#{version}/backbone-relational.min.js"
    when "jquery.dataTables"
      javascript_include_tag "#{boot}/datatables/#{version}/js/jquery.dataTables.min.js"
    when "handlebars"
      javascript_include_tag "#{boot}/handlebars.js/#{version}/handlebars.min.js"
    when "bootstrap"
      javascript_include_tag "#{boot}/bootstrap/#{version}/js/bootstrap.min.js"
    end
  end
</pre></code>

### And for flatpickr
change the following 2 lines of the file /Autolab/app/views/layouts/application.html.erb
<pre><code>
<%= stylesheet_link_tag "https://cdn.bootcss.com/flatpickr/4.2.4/flatpickr.min.css" %>
<%= javascript_include_tag "https://cdn.bootcss.com/flatpickr/4.2.4/flatpickr.min.js" %>
</pre><code>

### I suggest:
- Put the flatpickr also into the application_helper.rb file for for consistency.
- Add an option (bootcdn) for Chinese Student in the application_helper.rb file.

This is also a reminder for Chinese users :)

**Comment by zyx-billy** [comment]
Thanks for the notice! I'm not sure about adding an alternative cdn to the codebase since everyone may have their own needs and preferences. I think a better way is to make the cdn into something that can be configured (with the current ones being the default), though I'm not sure what the best way to do that would be. Perhaps others can chime in on whether they think this is big enough to warrant a move into the configs, or if we can just keep it where it is and just have people modify this file for their own deployments.

Whatever the solution is though, flatpickr should be with the others for consistency. Thanks for the catch!

**Comment by victorhuangwq** [comment]
should move to include the javascript itself (perhaps as a gem) instead of getting it from cdn

**Comment by damianhxy** [comment]
Closing this with #1535 which migrates flatpickr to `application_helper.rb`.

Re: cdn, imo it's better to stick to traditional cdns like cloudflare rather than bootcss (e.g. for security reasons)
- it is easy enough for users to modify `external_stylesheet_link_tag` and `external_javascript_include_tag` as needed when deploying
- as Victor mentioned, we can consider using gems instead of cdn, but it should be noted that not every library is available (e.g. golden-layout), and some libraries are outdated (e.g. semantic-ui)

There are also a bunch of js files in `assets/javascript` (e.g. d3, SlickGrid) that might be better off accessed from gems / cdn as otherwise I doubt anyone will know and/or care to update them.
