### ISSUE TITLE
Grades not accurately shown on assignment and gradebook

### ISSUE THREAD

**Issue by clairecw** [autolab/Autolab#979]
The scores for one of my assignments are not being updated on the assignment page (I contacted the course instructor directly and they inputted a different score than appears on my end). These changes have also not been reflected in my gradebook.

For another assignment in the same class, my scores all show up as 0, despite having nonzero scores one I click on the Autograder output. The grade for this assignment in the gradebook is also 0.
<img width="1680" alt="screen shot 2018-04-24 at 8 58 52 pm" src="https://user-images.githubusercontent.com/4808472/39222858-ebe76132-480c-11e8-8525-723d7afc85c2.png">
<img width="1680" alt="screen shot 2018-04-24 at 8 59 02 pm" src="https://user-images.githubusercontent.com/4808472/39222859-ebf7079a-480c-11e8-9f47-257009a5e209.png">
<img width="1680" alt="screen shot 2018-04-24 at 8 59 15 pm" src="https://user-images.githubusercontent.com/4808472/39222860-ec03ce1c-480c-11e8-8058-b700ccc24f4f.png">
<img width="1680" alt="screen shot 2018-04-24 at 9 06 10 pm" src="https://user-images.githubusercontent.com/4808472/39222861-ec0fbb1e-480c-11e8-9540-41285b55cd09.png">

**Comment by devanshk** [comment]
Hi Claire,

For Homework 7 - This is likely due to a bug your professor found today
when re-running the autograder on all submissions. We've pushed a hotfix
and the scores should be back to normal once it's deployed and he reruns
the autograder.

For Homework 8 - It appears the autograder is using different names for the
problems. The final json string should look something like

{"scores": {"files": 0, "compile": 0, "funcmonoid": 5, "treemap": 2,
"strategy": 15, "simple": 8, "stringmonoid": 3, "optmap": 2, "smart": 17,
"optmonad": 5}}


instead of


{"scores": {"files": 0, "compile": 0, "Simple - move_up": 1, "Monoid -
StringMonoid": 3, "Mappable - OptMap": 2, "Elevator_Strategy - decide": 15,
"Simple - downDecide2": 3, "Simple - init/snapshot": 5, "Smart -
init/snapshot": 9, "Smart - upDecide1": 1, "Monoid - FuncMonoid": 5, "Smart
- downDecide2": 1, "Simple - upDecide1": 3, "Smart - downDecide1": 0,
"Smart - move_up": 3, "Monad - OptMonad": 5, "Simple - move_down": 1,
"Smart - move_down": 3, "Simple - downDecide1": 3, "Mappable - TreeMap": 5}}


I imagine your professor was experimenting with ways to get around the bug,
but you can forward this note to him to check in.

**Comment by devanshk** [comment]
Closing this as it appears to have been resolved
